<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="18" time="0.042" timestamp="2022-11-04T10:23:36.710567" hostname="EPRSNOVW0017"><testcase classname="tests.test_accum" name="test_accumulator_init" time="0.000" /><testcase classname="tests.test_accum" name="test_accumulator_add_one" time="0.000" /><testcase classname="tests.test_accum" name="test_accumulator_add_three" time="0.000" /><testcase classname="tests.test_accum" name="test_accumulator_add_twice" time="0.000" /><testcase classname="tests.test_accum" name="test_accumulator_cant_set_count_directly" time="0.000" /><testcase classname="tests.test_chapter3" name="test_divide_by_zero" time="0.000" /><testcase classname="tests.test_chapter4" name="test_multiplication_two_positive_int" time="0.000" /><testcase classname="tests.test_chapter4" name="test_multiply_by_1" time="0.000" /><testcase classname="tests.test_chapter4" name="test_multiple_by_zero" time="0.000" /><testcase classname="tests.test_chapter4" name="test_multiplication[2-3-6]" time="0.000" /><testcase classname="tests.test_chapter4" name="test_multiplication[1-99-99]" time="0.000" /><testcase classname="tests.test_chapter4" name="test_multiplication[0-99-0]" time="0.000" /><testcase classname="tests.test_chapter4" name="test_multiplication[3--4--12]" time="0.000" /><testcase classname="tests.test_chapter4" name="test_multiplication[-5--5-25]" time="0.000" /><testcase classname="tests.test_chapter4" name="test_multiplication[2.5-6.7-16.75]" time="0.000" /><testcase classname="tests.test_math" name="test_one_plus_one" time="0.000" /><testcase classname="tests.test_math" name="test_one_plus_two" time="0.000"><failure message="assert (1 + 2) == 0">def test_one_plus_two():
        a = 1
        b = 2
        c = 0
&gt;       assert a + b == c
E       assert (1 + 2) == 0

tests/test_math.py:15: AssertionError</failure></testcase><testcase classname="tests.test_math" name="test_divide_by_zero" time="0.000"><failure message="ZeroDivisionError: division by zero">def test_divide_by_zero():
        a = 1
        b = 0
&gt;       assert a / b == 0
E       ZeroDivisionError: division by zero

tests/test_math.py:21: ZeroDivisionError</failure></testcase></testsuite></testsuites>